name: klinik_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.3.8
  get_storage: 2.0.1
  pretty_dio_logger: ^1.1.1
  dio: ^3.0.1
  google_fonts: any
  cached_network_image:
  carousel_slider: 3.0.0
  flutter_svg: 0.21.0-nullsafety.0
  flutter_staggered_grid_view: 0.3.4
  onboarding: ^1.0.5
  fancy_on_boarding: ^1.7.0
  flutter_datetime_picker: ^1.5.0
  pinput: ^1.2.0
  flutter_html:
  url_launcher: 6.0.2
  retrofit: 1.3.4+1
  shared_preferences: ^2.0.5
  linkwell:
  share_plus: ^3.0.2
  auto_direction: ^0.0.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  change_app_package_name: ^1.0.0
  retrofit_generator: any
  build_runner: any

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
    - assets/locales/
